TODO.md, slice/example_test.go, tests/benchmark/slice/slice_test.go
- Adds slice examples
- Removes methods that will be not implemented from TODO
For a better documetation
Implementing example_test.go in slice package
=> add slice examples

kv/example_test.go
Adds kv examples
For a better documentation
Implementing example_test.go in slice package
=> add kv examples

kv/collection.go, kv/collection_test.go, tests/benchmark/kv/kv_test.go
Add forget method 
TODO told me 
Adding a method called Forget 😄
=> add forget

generic.go, generic_test.go, matcher.go, matchers_test.go, support_test.go
Adds `FirstWhere` - which returns the first matching item, and `FirstWhereField` - which  returns the first value where the struct field value (accessed by name) matches.
It's part of the Laravel Collection - the interface is slightly different than Laravel's, though.
Besides adding the methods, custom matches were added to allow for deeper queries.
=> Add first where generic methods

TODO.md, generic.go, generic_test.go, kv/ordered/numeric/collection.go, kv/ordered/numeric/collection_test.go
Add duplicates
https://laravel.com/docs/9.x/collections#method-duplicates
`TODO.md`
Use `Tally` and then remove elements whose frequency is 1.
=> add duplicates

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/zip_test.go
Add generic `Zip`
take the length of the smallest slice as the output length, and then go through each index of the pre-allocated result and set the value to the corresponding values on the indexes of the argument slices.
=> feat(generic): add zip

generic.go, generic_test.go, tests/benchmark/generic/unique_test.go, tests/benchmark/generic/zip_test.go
Add `Unique`
by going through each value, using a map to remember seen values, and returning all values seen once
=> feat(generic): add unique

generic.go, generic_test.go, tests/benchmark/generic/diff_test.go
=> refactor generic diff

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/unique_by_test.go
Add generic `UniqueBy`
Basically the same code as `Unique`, but remembering distinct values using the return value of the provided function
=> feat(generic): add `UniqueBy`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/group_by_test.go
add `GroupBy`
By going through each element in the slice and storing it in a map using the return value of `f` as the key
=> feat(generic): add `GroupBy`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/partition_test.go
add `Partition`
by going through each element calling `f` and accumulating the values in separate arrays based on the return value of `f`
=> feat(generic): add partition

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/chunk_test.go
Add `Chunk`
Preallocate memory for the result and then go through each item in the slice in add it to the result using the index
=> feat(generic): add `Chunk`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/reverse_test.go
add `Reverse`
classic reverse algorithm
=> feat(generic): add `Reverse`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/sum_by_test.go
add `SumBy`
By accumulating values returned by the callback
=> feat(generic): add `SumBy`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/range_test.go
add `Range`
preallocate the slice and go through each index and set the value to index+min
=> feat(generic): add `Range`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/key_by_test.go
add `KeyBy`
https://laravel.com/docs/9.x/collections#method-keyby
going through each element in the slice and assigning it to the result map in the key `f(item)`
=> feat(generic): add `KeyBy`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/random_test.go
add `Random`
https://laravel.com/docs/9.x/collections#method-random
using `rand.Intn` to get a random index out of `slice`
=> feat(generic): add `Random`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/skip_test.go
add `Skip`
https://laravel.com/docs/9.x/collections#method-skip
using slices
=> feat(generic): add `Skip`

TODO.md, generic.go, generic_test.go, matcher.go, matchers_test.go, tests/benchmark/generic/skip_while_test.go
add `SkipWhile`
https://laravel.com/docs/9.x/collections#method-skipwhile
adding a `Not` matcher and using `SkipUntil`
=> feat(generic): add `SkipWhile`

generic.go, generic_test.go, tests/benchmark/generic/nth_offset_test.go, tests/benchmark/generic/nth_test.go
Adds `Nth` and `NthOffset`
TODO list.
By creating a slice of the expected size and appending every nth element from the given slice to it.
=> feat(generic): add `Nth` and `NthOffset`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/sliding_test.go
add `Sliding`
https://laravel.com/docs/9.x/collections#method-sliding
using slice ranges to accumulate the windows
=> feat(generic): add `Sliding`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/sort_by_test.go
add `SortBy`
https://laravel.com/docs/9.x/collections#method-sortby
using `sort.Slice` and comparing using `f`
=> feat(generic): add `SortBy`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/sort_by_desc_test.go
add `SortByDesc`
https://laravel.com/docs/9.x/collections#method-sortbydesc
same as `SortBy` but using `i > j`
=> feat(generic): add `SortByDesc`

TODO.md, generic.go, generic_test.go, internal/relational.go, tests/benchmark/generic/split_test.go
add `Split`
https://laravel.com/docs/9.x/collections#method-split
Coping the algorithm from Larevel https://github.com/laravel/framework/blob/a615378002db978339493e9af05be9c81cf3187f/src/Illuminate/Collections/Collection.php#L1174-L1203
=> feat(generic): add `Split`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/intersect_test.go
Add `Intersect` method.
It's on the `TODO` list.
By creating a "seen" map to check items that are present in both slices.
=> feat(generic): add `Intersect`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/take_test.go
add `Take`
https://laravel.com/docs/9.x/collections#method-take
checking boundaries and retuning a slice
=> feat(generic): add `Take`

TODO.md, generic.go, generic_test.go, tests/benchmark/generic/take_until_test.go
add `TakeUntil`
https://laravel.com/docs/9.x/collections#method-takeuntil
By calling `TakeWhile` with an inverted matcher
=> feat(generic): add `TakeUntil`

TODO.md, generic.go, generic_test.go, tests/benchmark/base.go, tests/benchmark/generic/times_test.go
add `Times`
https://laravel.com/docs/9.x/collections#method-times
preallocating a slice of size `n` and setting each position to the result of `f`
=> feat(generic): add `Times`

errors/errors.go, generic.go, generic_test.go, kv/collection.go, kv/collection_test.go, kv/ordered/collection.go, kv/ordered/collection_test.go, kv/ordered/numeric/collection.go, kv/ordered/numeric/collection_test.go, matcher.go, numeric.go, slice/collection.go, slice/collection_test.go, tests/benchmark/slice/slice_test.go
apply GoLand automatic fixes to GoLand warnings
I think they make sense
clicking IDE buttons like the Aztecs did thousands of years ago
=> fix: GoLand warnings

generic.go
use internal `DivCeil`
it's _cleaner_ ™️
changing the code (woah)
=> refactor(generic): use internal ceil

slice/collection.go, slice/collection_test.go, tests/benchmark/slice/slice_test.go
add `Reverse` to the slice collection
this PR uses the code added on #95, so we have to merge that one first
because I want to reverse stuff
using the generic function
=> feat(slice): add `Reverse`
